fix mount echo

diff --git a/cifs b/cifs
--- a/cifs
+++ b/cifs
@@ -57,163 +57,180 @@ set -u
 
 
 # The log file content has changed
-# Format is 
+# Format is
 # date +%F+%T STATUS STRING
 # STATUS can be SUCCESS WARNING DEBUG ERROR
-# Example 
+# Example
 #  2022-12-12+11:34:31 ERROR: cifs driver read bad values
 #  2022-12-12+11:35:15 DEBUG: cifs driver debug message
 #  2022-12-12+11:35:57 SUCCESS: { "command": "mount -t cifs", "networkPath": "bar", "mountPoint":"foo", "options":"username=USER", "exit": "0", "result" : "0" }
-# 
+#
 DATEFORMAT=+%F+%T
 ABCDESKTOPLOGPATH=/var/log/abcdesktop/cifs
 
 init() {
-	mkdir -p $ABCDESKTOPLOGPATH
-	assertBinaryInstalled mount.cifs cifs-utils
-	assertBinaryInstalled jq jq
-	assertBinaryInstalled mountpoint util-linux
-	assertBinaryInstalled base64 coreutils
-	echo '{ "status": "Success", "message": "The abcdesktop/cifs flexvolume plugin was initialized successfully", "capabilities": { "attach": false } }'
-	exit 0
+ mkdir -p $ABCDESKTOPLOGPATH
+ assertBinaryInstalled mount.cifs cifs-utils
+ assertBinaryInstalled jq jq
+ assertBinaryInstalled mountpoint util-linux
+ assertBinaryInstalled base64 coreutils
+ echo '{ "status": "Success", "message": "The abcdesktop/cifs flexvolume plugin was initialized successfully", "capabilities": { "attach": false } }'
+ exit 0
 }
 
 assertBinaryInstalled() {
-	binary="$1"
-	package="$2"
-	if ! which "$binary" > /dev/null ; then
-		errorExit "Failed to initialize the abcdesktop/cifs flexvolume plugin. $binary command not found. Please install the $package package."
-	fi
+ binary="$1"
+ package="$2"
+ if ! which "$binary" > /dev/null ; then
+  errorExit "Failed to initialize the abcdesktop/cifs flexvolume plugin. $binary command not found. Please install the $package package."
+ fi
+}
+
+traceDebug() {
+  echo $(date $DATEFORMAT) "$1" >> $ABCDESKTOPLOGPATH/trace.log
 }
 
 errorExit() {
-	if [[ $# -ne 1 ]] ; then
-		echo $(date $DATEFORMAT) errorExit:Unknown error in the abcdesktop/cifs flexvolume plugin. >> $ABCDESKTOPLOGPATH/error.log
-		echo '{ "status": "Failure", "message": "Unknown error in the abcdesktop/cifs flexvolume plugin." }'
-	else
-		echo $(date $DATEFORMAT) errorExit:$1 >> $ABCDESKTOPLOGPATH/error.log
-		jq -Mcn --arg message "$1" '{ "status": "Failure", "message": $message }'
-	fi
-	exit 1
+ if [[ $# -ne 1 ]] ; then
+  echo $(date $DATEFORMAT) errorExit:Unknown error in the abcdesktop/cifs flexvolume plugin. >> $ABCDESKTOPLOGPATH/error.log
+  echo '{ "status": "Failure", "message": "Unknown error in the abcdesktop/cifs flexvolume plugin." }'
+ else
+  echo $(date $DATEFORMAT) errorExit:$1 >> $ABCDESKTOPLOGPATH/error.log
+  jq -Mcn --arg message "$1" '{ "status": "Failure", "message": $message }'
+ fi
+ exit 1
 }
 
 doMount() {
-	cifsDomain=''		# set empty string by default for domain value
-	mountDomain=''
+ cifsDomain=''  # set empty string by default for domain value
+ mountDomain=''
+ traceDebug "read"
 
-	if [[ -z ${1:-} || -z ${2:-} ]] ; then
-		errorExit "cifs mount: syntax error. usage: cifs mount <mount dir> <json options>"
-	fi
-	mountPoint="$1"
-	shift
-	json=$(printf '%s ' "${@}")
-	if ! jq -e . > /dev/null 2>&1 <<< "$json" ; then
-		errorExit "cifs mount: syntax error. invalid json: '$json'"
-	fi
-	networkPath="$(jq --raw-output -e '.networkPath' <<< "$json" 2>/dev/null)"
-	if [[ $? -ne 0 ]] ; then
-		errorExit "cifs mount: option networkPath missing in flexvolume configuration."
-	fi
-	mountOptions="$(jq --raw-output -e '.mountOptions' <<< "$json" 2>/dev/null)"
-	if [[ $? -ne 0 ]] ; then
-		errorExit "cifs mount: option mountOptions missing in flexvolume configuration."
-	fi
-	cifsUsernameBase64="$(jq --raw-output -e '.["kubernetes.io/secret/username"]' <<< "$json" 2>/dev/null)"
-	if [[ $? -ne 0 ]] ; then
-		errorExit "cifs mount: username not found. the flexVolume definition must contain a secretRef to a secret with username and password."
-	fi
-	cifsPasswordBase64="$(jq --raw-output -e '.["kubernetes.io/secret/password"]' <<< "$json" 2>/dev/null)"
-	if [[ $? -ne 0 ]] ; then
-		errorExit "cifs mount: password not found. the flexVolume definition must contain a secretRef to a secret with username and password."
-	fi
+ if [[ -z ${1:-} || -z ${2:-} ]] ; then
+  errorExit "cifs mount: syntax error. usage: cifs mount <mount dir> <json options>"
+ fi
 
-	cifsDomainBase64="$(jq --raw-output -e '.["kubernetes.io/secret/domain"]' <<< "$json" 2>/dev/null)"
-    # cifsDomainBase64 is an option, it can be undefined	
+ mountPoint="$1"
+ shift
+ json=$(printf '%s ' "${@}")
+ if ! jq -e . > /dev/null 2>&1 <<< "$json" ; then
+  errorExit "cifs mount: syntax error. invalid json: '$json'"
+ fi
+ networkPath="$(jq --raw-output -e '.networkPath' <<< "$json" 2>/dev/null)"
+ if [[ $? -ne 0 ]] ; then
+  errorExit "cifs mount: option networkPath missing in flexvolume configuration."
+ fi
+ mountOptions="$(jq --raw-output -e '.mountOptions' <<< "$json" 2>/dev/null)"
+ if [[ $? -ne 0 ]] ; then
+  errorExit "cifs mount: option mountOptions missing in flexvolume configuration."
+ fi
+ cifsUsernameBase64="$(jq --raw-output -e '.["kubernetes.io/secret/username"]' <<< "$json" 2>/dev/null)"
+ if [[ $? -ne 0 ]] ; then
+  errorExit "cifs mount: username not found. the flexVolume definition must contain a secretRef to a secret with username and password."
+ fi
+ cifsPasswordBase64="$(jq --raw-output -e '.["kubernetes.io/secret/password"]' <<< "$json" 2>/dev/null)"
+ if [[ $? -ne 0 ]] ; then
+  errorExit "cifs mount: password not found. the flexVolume definition must contain a secretRef to a secret with username and password."
+ fi
+ cifsDomainBase64="$(jq --raw-output -e '.["kubernetes.io/secret/domain"]' <<< "$json" 2>/dev/null)"
+ # cifsDomainBase64 is an option, it can be undefined
+ traceDebug "read done"
+ traceDebug "base64"
 
-	cifsUsername="$(base64 --decode <<< "$cifsUsernameBase64" 2>/dev/null)"
-	if [[ $? -ne 0 ]] ; then
-		errorExit "cifs mount: username secret is not base64 encoded."
-	fi
-	cifsPassword="$(base64 --decode <<< "$cifsPasswordBase64" 2>/dev/null)"
-	if [[ $? -ne 0 ]] ; then
-		errorExit "cifs mount: password secret is not base64 encoded."
-	fi
 
-	cifsDomain="$(base64 --decode <<< "$cifsDomainBase64" 2>/dev/null)"
-	if [[ $? -eq 0 ]] ; then
-			mountOptions=$mountOptions,domain=$cifsDomain
-			echo  "$(date $DATEFORMAT) DEBUG: mountOptions=$mountOptions" >> $ABCDESKTOPLOGPATH/$cifsUsername.log
-	fi
+ cifsUsername="$(base64 --decode <<< "$cifsUsernameBase64" 2>/dev/null)"
+ if [[ $? -ne 0 ]] ; then
+  errorExit "cifs mount: username secret is not base64 encoded."
+ fi
+ cifsPassword="$(base64 --decode <<< "$cifsPasswordBase64" 2>/dev/null)"
+ if [[ $? -ne 0 ]] ; then
+  errorExit "cifs mount: password secret is not base64 encoded."
+ fi
 
-	mkdir -p "$mountPoint" > /dev/null 2>&1 
-	if [[ $? -ne 0 ]] ; then
-		errorExit "cifs mount: failed to create mount directory: '$mountPoint'"
-	fi
+ cifsDomain="$(base64 --decode <<< "$cifsDomainBase64" 2>/dev/null)"
+ if [[ $? -eq 0 ]] ; then
+   mountOptions=$mountOptions,domain=$cifsDomain
+   echo  "$(date $DATEFORMAT) DEBUG: mountOptions=$mountOptions" >> $ABCDESKTOPLOGPATH/$cifsUsername.log
+ fi
 
-	mountpoint "$mountPoint" 1>/dev/null 2>/dev/null
-	if [[ $? -eq 0 ]] ; then
-		echo "$(date) WARNING: cifs mount: there is already a filesystem mounted under the mount directory: $mountPoint" >> $ABCDESKTOPLOGPATH/$cifsUsername.log
-		# errorExit "cifs mount: already a mount point $mountPoint" 
-		echo { \"status\": \"Success\", \"command\": "0" }
-		exit 0
-	fi
 
-	# mount directory is not an empty directory 
-	if [[ ! -z $(ls -A "$mountPoint" 2>/dev/null) ]] ; then
-		errorExit "cifs mount: mount directory is not an empty directory: '$mountPoint'"
-	fi
+ traceDebug "base64 done"
+ traceDebug "mountpoint"
+ mkdir -p "$mountPoint" > /dev/null 2>&1
+ if [[ $? -ne 0 ]] ; then
+  errorExit "cifs mount: failed to create mount directory: '$mountPoint'"
+ fi
 
-	export PASSWD="$cifsPassword"
-	echo "$(date) DEBUG: mount -t cifs $networkPath $mountPoint -o username=$cifsUsername,$mountOptions"
-	result=$(mount -t cifs "$networkPath" "$mountPoint" -o "username=$cifsUsername,$mountOptions" 2>&1)
-	code=$?
-	# code is the exit code of previous command
-	if [[ $code -ne 0 ]] ; then
-		# remove the previous created directory
-		rmdir "$mountPoint" 1>/dev/null 2>>$ABCDESKTOPLOGPATH/$cifsUsername.json
-		echo  "$(date $DATEFORMAT) ERROR: cifs driver get input $json" >> $ABCDESKTOPLOGPATH/$cifsUsername.json
-		echo  "$(date $DATEFORMAT) ERROR: { \"command\": \"mount -t cifs\", \"networkPath\": \"$networkPath\", \"mountPoint\":\"$mountPoint\", \"options\":\"-o username=$cifsUsername,$mountOptions\", \"exit\": \"$code\", \"result\" : \"$result\" }" >> $ABCDESKTOPLOGPATH/$cifsUsername.log
-		errorExit "cifs mount: failed to mount the network path: $result"
-	fi
-	echo "$(date $DATEFORMAT) SUCCESS: { \"command\": \"mount -t cifs\", \"networkPath\": \"$networkPath\", \"mountPoint\":\"$mountPoint\", \"options\":\"username=$cifsUsername,$mountOptions\", \"exit\": \"$code\", \"result\" : \"$result\" }" >> $ABCDESKTOPLOGPATH/$cifsUsername.log
-	echo { \"status\": \"Success\", \"command\": "$code" }
-	exit 0
+ mountpoint "$mountPoint" 1>/dev/null 2>/dev/null
+ if [[ $? -eq 0 ]] ; then
+  echo "$(date) WARNING: cifs mount: there is already a filesystem mounted under the mount directory: $mountPoint" >> $ABCDESKTOPLOGPATH/$cifsUsername.log
+  # errorExit "cifs mount: already a mount point $mountPoint"
+  echo { \"status\": \"Success\", \"command\": "0" }
+  exit 0
+ fi
+
+ # mount directory is not an empty directory
+ if [[ ! -z $(ls -A "$mountPoint" 2>/dev/null) ]] ; then
+  errorExit "cifs mount: mount directory is not an empty directory: '$mountPoint'"
+ fi
+
+ traceDebug "mountpoint done"
+ traceDebug "mountcifs"
+ export PASSWD="$cifsPassword"
+ traceDebug "mount -t cifs $networkPath $mountPoint -o username=$cifsUsername,$mountOptions"
+ echo "$(date) DEBUG: mount -t cifs $networkPath $mountPoint -o username=$cifsUsername,$mountOptions" >> $ABCDESKTOPLOGPATH/$cifsUsername.log
+ result=$(mount -t cifs "$networkPath" "$mountPoint" -o "username=$cifsUsername,$mountOptions" 2>&1)
+ code=$?
+ traceDebug "mountcifs done"
+ traceDebug "mount return $code $result" 
+
+ # code is the exit code of previous command
+ if [[ $code -ne 0 ]] ; then
+  # remove the previous created directory
+  rmdir "$mountPoint" 1>/dev/null 2>>$ABCDESKTOPLOGPATH/$cifsUsername.json
+  echo  "$(date $DATEFORMAT) ERROR: cifs driver get input $json" >> $ABCDESKTOPLOGPATH/$cifsUsername.json
+  echo  "$(date $DATEFORMAT) ERROR: { \"command\": \"mount -t cifs\", \"networkPath\": \"$networkPath\", \"mountPoint\":\"$mountPoint\", \"options\":\"-o username=$cifsUsername,$mountOptions\", \"exit\": \"$code\", \"result\" : \"$result\" }" >> $ABCDESKTOPLOGPATH/$cifsUsername.log
+  errorExit "cifs mount: failed to mount the network path: $result"
+ fi
+ echo "$(date $DATEFORMAT) SUCCESS: { \"command\": \"mount -t cifs\", \"networkPath\": \"$networkPath\", \"mountPoint\":\"$mountPoint\", \"options\":\"username=$cifsUsername,$mountOptions\", \"exit\": \"$code\", \"result\" : \"$result\" }" >> $ABCDESKTOPLOGPATH/$cifsUsername.log
+ echo { \"status\": \"Success\", \"command\": "$code" }
+ exit 0
 }
 
 doUnmount() {
-	if [[ -z ${1:-} ]] ; then
-		errorExit "cifs unmount: syntax error. usage: cifs unmount <mount dir>"
-	fi
-	mountPoint="$1"
-	result=$(umount "$mountPoint" 2>&1)
-	if [[ $? -ne 0 ]] ; then
-		errorExit "cifs unmount: failed $mountPoint is not a mount $result"
-	fi
-	echo '{ "status": "Success" }'
-	exit 0
+ if [[ -z ${1:-} ]] ; then
+  errorExit "cifs unmount: syntax error. usage: cifs unmount <mount dir>"
+ fi
+ mountPoint="$1"
+ result=$(umount "$mountPoint" 2>&1)
+ if [[ $? -ne 0 ]] ; then
+  errorExit "cifs unmount: failed $mountPoint is not a mount $result"
+ fi
+ echo '{ "status": "Success" }'
+ exit 0
 }
 
 not_supported() {
-	echo '{ "status": "Not supported" }'
-	exit 1
+ echo '{ "status": "Not supported" }'
+ exit 1
 }
 
 command=${1:-}
 if [[ -n $command ]]; then
-	shift
+ shift
 fi
 
 case "$command" in
-	init)
-		init "$@"
-		;;
-	mount)
-		doMount "$@"
-		;;
-	unmount)
-		doUnmount "$@"
-		;;
-	*)
-		not_supported "$@"
-		;;
+ init)
+  init "$@"
+  ;;
+ mount)
+  doMount "$@"
+  ;;
+ unmount)
+  doUnmount "$@"
+  ;;
+ *)
+  not_supported "$@"
+  ;;
 esac
